import { Rubik } from "next/font/google";
import Sidenav from "@/components/controlpanel/Sidenav";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const rubik = Rubik({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Bidsforce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <link
        rel="stylesheet"
        href="/assets/vendor/fonts/materialdesignicons.css"
      />
      <link
        rel="stylesheet"
        href="/assets/vendor/libs/node-waves/node-waves.css"
      />
      <link
        rel="stylesheet"
        href="/assets/vendor/css/core.css"
        class="template-customizer-core-css"
      />
      <link
        rel="stylesheet"
        href="/assets/vendor/css/theme-default.css"
        class="template-customizer-theme-css"
      />
      <link
        rel="stylesheet"
        href="/assets/css/customize.css"
        class="template-customizer-theme-custom-css"
      />

      <div className="flex layout-wrapper layout-content-navbar">
        <div class="layout-container">
          <Sidenav />
          <div className="w-full layout-page">
            <Navbar />
            <div className="p-7 bg-[#F2F4F6] min-h-[100vh]">{children}</div>

            <div
              class="alert alert-danger alert-dismissible position-fixed bottom-3 w-50 mx-4"
              style={{ display: "none" }}
              role="alert"
              id="errorMessageAlert"
            >
              <b className="title">Error:</b>
              <div className="body">Error in operaton.</div>
              <button
                type="button"
                class="btn-close"
                data-bs-dismiss="alert"
                aria-label="Close"
              ></button>
            </div>
          </div>
        </div>
      </div>

      <script src="/assets/vendor/js/helpers.js" async></script>
      <script src="/assets/vendor/js/menu.js" async></script>
      <script src="/assets/js/main.js" async></script>
    </>
  );
}
