import { Rubik } from 'next/font/google'
import Sidenav from '@/components/usermanager/Sidenav'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const rubik = Rubik({
    weight: ['300', '400', '500', '600', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
})
export const metadata = {
    title: 'Bidsforce',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

    return (
        <div className='flex'>
            <Sidenav />
            <div className='w-full'>
            <Navbar />
                <div className='p-7 bg-[#F2F4F6] min-h-[100vh]'  >
                    {children}
                </div>
                <Footer />
            </div>
        </div>
    )
}
