import { Rubik } from 'next/font/google'
import './globals.css'
import './style.css'
import Head from 'next/head'
import ReactDOM from 'react-dom';

const rubik = Rubik({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: 'Bidsforce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  

  return (

    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${rubik.className} `} >{children}</body>
    </html>

  )
}
