import { Rubik } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import ManagerSidenav from '@/components/ManagerSidenav'
import { SidebarProvider } from '@/context/SidebarContext/SidebarProvider'

const rubik = Rubik({
    weight: ['300', '400', '500', '600', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
})
export const metadata = {
    title: 'Bidsforce',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

    return (
        <div className='flex'>
            <SidebarProvider>
                <ManagerSidenav />
                <div className='w-full max-w-[calc(100% - 250px)]'>
                    <Navbar />
                    <div className='p-7 bg-[#F2F4F6] min-h-[100vh] mb-10 h-full max-w-full'  >
                        {children}
                    </div>
                    <Footer />
                </div>
            </SidebarProvider>
        </div>
    )
}
