import { Rubik } from 'next/font/google';
import SideNavAdminPanel from './components/Sidenav';
import AdminPanelNavbar from './components/Navbar';
import "./assets/vendor/fonts/materialdesignicons.css"
import "./assets/vendor/libs/node-waves/node-waves.css"
import "./assets/vendor/css/core.css"
import "./assets/vendor/css/theme-default.css"
import "./assets/css/demo.css"
import "./assets/css/bootstrap.min.css"

const rubik = Rubik({
    weight: ['300', '400', '500', '600', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});

export const metadata = {
    title: 'Bidsforce',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html>

            <head>
                <title>{metadata.title}</title>
                <meta name="description" content={metadata.description} />
            </head>
            <body>

                <div className='flex layout-wrapper layout-content-navbar'>
                    <div className="layout-container">
                        <SideNavAdminPanel />
                        <div className='w-full layout-page'>
                            <AdminPanelNavbar />
                            <div className='p-7 bg-[#F2F4F6] min-h-[100vh]'  >
                                {children}
                            </div>
                            <div className="alert alert-danger alert-dismissible position-fixed bottom-3 w-50 mx-4" style={{ display: "none" }} role="alert" id="errorMessageAlert">
                                <b className="title">Error:</b>
                                <div className="body">Error in operaton.</div>
                                <button type="button" className="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        </div>
                    </div>
                </div>

                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js" async></script>
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" async integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></script>
                <script src="/assets/vendor/js/helpers.js" async ></script>
                <script src="/assets/vendor/js/menu.js" async ></script>
                <script src="/assets/js/main.js" async ></script>
            </body>
        </html>

    );
}
